-- =============================================================================
-- 0002_roles.sql — least-privilege database roles
--
-- Three roles, because the three things that talk to this database deserve
-- three different levels of trust:
--
--   sxc_web     the public site. Internet-facing, therefore the least trusted
--               thing here. It can read the directory and let an alumnus edit
--               their own row. It cannot grant access, cannot touch an admin
--               account, cannot approve a photograph, and cannot rewrite
--               history. A total compromise of the public site still cannot
--               mint itself an allowlist entry.
--
--   sxc_admin   the admin portal. Full control of the data, but audit_log is
--               still insert-only for it.
--
--   sxc_ingest  the local ingest tool. Loads the directory and builds the
--               allowlist, then goes away. Deliberately separate so the admin
--               portal's credentials never need to sit on a laptop.
--
-- None of them may create, alter or drop anything. Schema changes come from a
-- migration run by the owner, never from a running application.
--
-- Apply with three passwords generated by a password manager:
--
--   psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 \
--     -v web_password="..." -v admin_password="..." -v ingest_password="..." \
--     -f db/migrations/0002_roles.sql
--
-- Passwords are shell-quoted here; put them in the password manager, not in
-- shell history. (`HISTCONTROL=ignorespace` and a leading space, or better,
-- read them from the manager's CLI.)
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- Roles
-- -----------------------------------------------------------------------------

create role sxc_web    login password :'web_password'    nocreatedb nocreaterole noinherit;
create role sxc_admin  login password :'admin_password'  nocreatedb nocreaterole noinherit;
create role sxc_ingest login password :'ingest_password' nocreatedb nocreaterole noinherit;

grant usage on schema public to sxc_web, sxc_admin, sxc_ingest;

-- No role may add objects to the schema. Combined with the absence of any
-- ALTER/DROP grant, the application cannot change its own shape (plan §10.6).
revoke create on schema public from public, sxc_web, sxc_admin, sxc_ingest;

-- Start from nothing and hand back exactly what each role needs.
revoke all on all tables in schema public from sxc_web, sxc_admin, sxc_ingest;
revoke all on all sequences in schema public from sxc_web, sxc_admin, sxc_ingest;


-- -----------------------------------------------------------------------------
-- sxc_web — the public site
-- -----------------------------------------------------------------------------

-- The directory. SELECT is unrestricted at the SQL level because the tier
-- filtering happens in the data-access module (plan §5.2); what matters here is
-- that the write surface is a short, named list of columns.
grant select on alumni to sxc_web;

-- Exactly the fields an alumnus owns on /me (plan §7.1). Everything absent from
-- this list — full_name, batch_year, stream, gmail_enc, gmail_hmac,
-- form_email_enc, consent_recorded_at, photo_reviewed_by — is unwritable by the
-- public application no matter what a future bug in it tries to do.
--
-- Note: updated_at is set by the alumni_touch trigger, and column privileges
-- are checked against the columns named in the statement rather than those a
-- trigger writes, so it is deliberately not granted.
grant update (
  contact_enc,
  other_info_enc,
  current_org,
  designation,
  previous_role,
  show_contact,
  show_gmail,
  photo_audience,
  photo_path,
  photo_status,
  photo_updated_at,
  is_visible,
  owner_updated_at
) on alumni to sxc_web;

-- The allowlist is readable so login can check it, and writable by nobody here.
grant select on access_grant to sxc_web;

-- Magic links: mint, look up, consume.
grant select, insert, update on login_token to sxc_web;

-- Sessions: create, read, touch, revoke, delete.
grant select, insert, update, delete on session to sxc_web;

-- Access requests: the public form creates them and the OTP step updates them.
-- Deciding them is the admin portal's job and is not granted.
grant select, insert, update on access_request to sxc_web;

-- Rate limiting.
grant select, insert, update, delete on rate_limit to sxc_web;

-- Append-only audit. No SELECT: the public site writes history and never reads
-- it back, so a bug there cannot be turned into a way to read who viewed whom.
grant insert on audit_log to sxc_web;
grant usage on sequence audit_log_id_seq to sxc_web;

-- admin_user, admin_invite and admin_recovery_code are not granted at all.


-- -----------------------------------------------------------------------------
-- sxc_admin — the admin portal
-- -----------------------------------------------------------------------------

grant select, insert, update, delete on
  alumni, access_grant, login_token, session, access_request, rate_limit,
  admin_user, admin_invite, admin_recovery_code
to sxc_admin;

-- Even the admin portal cannot rewrite the audit log. The trigger in 0001 backs
-- this up, so widening the grant by accident is not enough to change history.
grant select, insert on audit_log to sxc_admin;
grant usage on sequence audit_log_id_seq to sxc_admin;


-- -----------------------------------------------------------------------------
-- sxc_ingest — the local Excel loader
-- -----------------------------------------------------------------------------

-- Loads and refreshes directory rows, and builds the allowlist from the sheet.
grant select, insert, update on alumni to sxc_ingest;
grant select, insert, update on access_grant to sxc_ingest;
grant insert on audit_log to sxc_ingest;
grant usage on sequence audit_log_id_seq to sxc_ingest;

-- No sessions, no admin tables, no deletes. A mistake during an import cannot
-- destroy a record or forge a login.


-- -----------------------------------------------------------------------------
-- Anything added later starts closed
-- -----------------------------------------------------------------------------

alter default privileges in schema public
  revoke all on tables from sxc_web, sxc_admin, sxc_ingest;
alter default privileges in schema public
  revoke all on sequences from sxc_web, sxc_admin, sxc_ingest;

commit;
