/**
 * Writing an admin account.
 *
 * Shared by the bootstrap CLI and the invitation flow so the two cannot drift.
 * A second implementation of "create an admin" is a second chance to forget the
 * TOTP confirmation, and the difference would not show up until someone signed
 * in without a second factor.
 *
 * ## The AAD dance
 *
 * Ciphertext is bound to its row id (plan §3.2), and the id is generated by the
 * database — so it is not known until the INSERT returns. The insert writes
 * both encrypted columns with a placeholder context, then rewrites them with
 * the real one, inside a single transaction. No other reader ever sees the
 * placeholder state, and a failure at any point leaves no row at all.
 *
 * The alternative — generating the uuid in JavaScript — would work, but the
 * database default is the thing every other table relies on, and having one
 * table mint its own ids differently is the kind of inconsistency that gets
 * copied.
 */

import { adminDb, type Sql } from './db.ts';
import { audit, encryptField, fieldContext } from './shared.ts';
import { hashPassword } from './password.ts';
import type { AdminRole } from './admin-session.ts';

export interface NewAdmin {
  /** Already normalised, as `emailBlindIndex` returns it. */
  normalisedEmail: string;
  emailHmac: Buffer;
  password: string;
  /** Base32 TOTP secret, already confirmed with a live code by the caller. */
  totpSecret: string;
  role: AdminRole;
  /** Who created this account. Null for the local bootstrap. */
  createdBy?: string | null;
  /** True when another admin set the password, so the owner must replace it. */
  mustChangePassword?: boolean;
}

/**
 * Insert an active admin with confirmed two-factor.
 *
 * There is deliberately no way to create an account with `totp_confirmed_at`
 * null through this function. The database backs that up:
 * `admin_active_requires_totp` (0001) refuses an active row without it.
 */
export async function createAdminAccount(admin: NewAdmin, sql: Sql = adminDb()): Promise<string> {
  const passwordHash = await hashPassword(admin.password);

  const adminId = await sql.begin(async (tx) => {
    const rows = await tx<Array<{ id: string }>>`
      insert into admin_user (
        email_enc, email_hmac, password_hash, totp_secret_enc,
        totp_confirmed_at, status, role, must_change_password
      ) values (
        ${encryptField(admin.normalisedEmail, fieldContext('admin_user', 'pending', 'email'))},
        ${admin.emailHmac},
        ${passwordHash},
        ${encryptField(admin.totpSecret, fieldContext('admin_user', 'pending', 'totpSecret'))},
        now(), 'active', ${admin.role}, ${admin.mustChangePassword ?? false}
      )
      returning id
    `;
    const id = rows[0]!.id;

    await tx`
      update admin_user
         set email_enc = ${encryptField(admin.normalisedEmail, fieldContext('admin_user', id, 'email'))},
             totp_secret_enc = ${encryptField(admin.totpSecret, fieldContext('admin_user', id, 'totpSecret'))}
       where id = ${id}
    `;

    return id;
  });

  await audit(
    {
      actorType: admin.createdBy ? 'admin' : 'system',
      actorId: admin.createdBy ?? 'admin:create',
      action: 'admin_created',
      targetType: 'admin_user',
      targetId: adminId,
      meta: { role: admin.role, via: admin.createdBy ? 'invitation' : 'local_cli' },
    },
    sql,
  );

  return adminId;
}
