// Merge the entrance-animation blobs of the four pages into one table.
// Framer keys each by `data-framer-appear-id` and, inside, by breakpoint hash
// ("default" is the desktop spec). Written by Framer, not measured, so the
// springs and delays are the site's own.
import fs from 'node:fs';
const merged = {};
for (const p of ['home', 'about-us', 'programs', 'contact-us']) {
  const blob = JSON.parse(fs.readFileSync(`D:/oxversity/_extract/appear-${p}.json`, 'utf8'));
  for (const [id, spec] of Object.entries(blob)) merged[id] = { ...(merged[id] || {}), ...spec };
}
fs.writeFileSync('D:/oxversity/src/data/appear.ts', `// Generated by _extract/appear.mjs from the pages' __framer__appearAnimationsContent
// blobs: the site's real entrance animations, keyed by data-framer-appear-id and
// then by breakpoint hash ("default" = desktop). Regenerate rather than hand-edit.
import type { EffectState, EffectTransition } from './effects';

export interface AppearSpec {
  initial: EffectState;
  animate: EffectState & { transition: EffectTransition };
}

export const appearAnimations: Record<string, Record<string, AppearSpec>> = ${JSON.stringify(merged, null, 2)};

/**
 * Framer's text effect on the "OX Versity" hero titles: each character starts
 * 80px low and transparent and springs up, 0.1s after the one before, once the
 * title's own entrance has been running for 0.4s.
 */
export const TEXT_EFFECT = {
  effect: { opacity: 0.001, rotate: 0, scale: 1, skewX: 0, skewY: 0, x: 0, y: 80 } as EffectState,
  startDelay: 0.4,
  stagger: 0.1,
  transition: { bounce: 0.25, duration: 1, type: 'spring' } as EffectTransition,
};
`);
console.log(Object.keys(merged).length, 'appear ids');
