// Pull Framer's inline stylesheets out of the live server-rendered pages into
// one file. Every page repeats the shared rules, so rules are split
// (brace-depth aware) and deduplicated by text. The breakpoint sheet and the
// font sheet are kept separate so their role stays legible.
import fs from 'node:fs';
import * as cheerio from 'cheerio';

const WORK = 'D:/exporter/exports/oxv/_work';
const EXPORT = 'D:/exporter/exports/oxv/ox-versity.framer.website';
const PAGES = ['live-home.html', 'live-about-us.html', 'live-programs.html', 'live-contact-us.html'];
const BACKSLASH = String.fromCharCode(92);

function splitRules(css) {
  const rules = [];
  let depth = 0;
  let start = 0;
  let str = null;
  let comment = false;
  for (let i = 0; i < css.length; i++) {
    const ch = css[i];
    const next = css[i + 1];
    if (comment) {
      if (ch === '*' && next === '/') { comment = false; i++; }
      continue;
    }
    if (str) {
      if (ch === BACKSLASH) { i++; continue; }
      if (ch === str) str = null;
      continue;
    }
    if (ch === '/' && next === '*') { comment = true; i++; continue; }
    if (ch === '"' || ch === "'") { str = ch; continue; }
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) { rules.push(css.slice(start, i + 1).trim()); start = i + 1; }
    }
  }
  const tail = css.slice(start).trim();
  if (tail) rules.push(tail);
  return rules;
}

// Insertion order matters: the same preset rule appears once as a base rule
// and again inside a media query, and the later one must win. Keeping the
// *last* occurrence of a duplicate preserves the cascade Framer relies on.
const main = new Set();
const breakpoints = new Set();
const keepLast = (set, rule) => { set.delete(rule); set.add(rule); };
let count = 0;
for (const p of PAGES) {
  const $ = cheerio.load(fs.readFileSync(`${WORK}/${p}`, 'utf8'));
  $('style[data-framer-css-ssr-minified], style[data-framer-css]').each((_, e) => {
    for (const r of splitRules($(e).html() || '')) { count++; keepLast(main, r); }
  });
  $('style[data-framer-breakpoint-css]').each((_, e) => {
    for (const r of splitRules($(e).html() || '')) breakpoints.add(r);
  });
  $('#main style').each((_, e) => {
    for (const r of splitRules($(e).html() || '')) keepLast(main, r);
  });
}

// Fonts: the export's declarations already point at local files.
const faces = new Set();
for (const p of ['index.html', 'about-us/index.html', 'programs/index.html', 'contact-us/index.html']) {
  const $ = cheerio.load(fs.readFileSync(`${EXPORT}/${p}`, 'utf8'));
  for (const r of splitRules($('style[data-framer-font-css]').html() || '')) {
    faces.add(r.replace(/(?:\.{1,2}\/)*assets\/fonts\//g, '/fonts/'));
  }
}

const header = (what) => `/* ${what}
 * Generated by _extract/extract-css.mjs from the Framer site's server-rendered pages.
 * Do not hand-edit: regenerate. Hand-written overrides live in site.css. */
`;
fs.writeFileSync('D:/oxversity/src/styles/framer.css', header('Framer component and preset CSS, the styling baseline.') + [...main].join('\n') + '\n');
fs.writeFileSync('D:/oxversity/src/styles/breakpoints.css', header("Framer's breakpoint switches: each ssr-variant copy is hidden outside its media query.") + [...breakpoints].join('\n') + '\n');
fs.writeFileSync('D:/oxversity/src/styles/fonts.css', header('@font-face declarations; the files live under /public/fonts.') + [...faces].join('\n') + '\n');
console.log(`${count} rules seen → ${main.size} unique; ${breakpoints.size} breakpoint rules; ${faces.size} font faces`);
