// Component CSS that only reaches the page at runtime. Framer ships each
// component's rules inside its JavaScript module and injects them when the
// component mounts; anything absent from the server render (the "Pages"
// dropdown, the search modal's list items…) is therefore missing from the
// extracted stylesheet. This scans the bundles for rule strings and keeps the
// ones whose component id the extracted stylesheet does not know.
import fs from 'node:fs';
import path from 'node:path';
const JS = 'D:/exporter/exports/oxv/ox-versity.framer.website/js';
const known = fs.readFileSync('D:/oxversity/src/styles/framer.css', 'utf8');
const knownIds = new Set([...known.matchAll(/\.framer-([A-Za-z0-9]{5})[\s.,{[:]/g)].map((m) => m[1]).filter((id) => /[A-Z]/.test(id)));
const rules = new Set();
for (const f of fs.readdirSync(JS).filter((f) => f.endsWith('.mjs'))) {
  const src = fs.readFileSync(path.join(JS, f), 'utf8');
  for (const m of src.matchAll(/[`"'](\.framer-([A-Za-z0-9]{5})[^`"']*\{[^`"']*\})[`"']/g)) {
    const id = m[2];
    if (!/[A-Z]/.test(id) || knownIds.has(id)) continue;
    if (m[1].includes('${')) continue; // a template literal, not a finished rule
    rules.add(m[1].replace(/\\"/g, '"'));
  }
}
const ids = new Set([...rules].map((r) => r.match(/\.framer-([A-Za-z0-9]{5})/)[1]));
fs.writeFileSync('D:/oxversity/src/styles/framer-runtime.css', `/* Component CSS Framer injects at runtime for components absent from the server render.
 * Generated by _extract/runtime-css.mjs. Do not hand-edit. */
${[...rules].join('\n')}
`);
console.log(rules.size, 'rules for components:', [...ids].join(' '));
