// Build the search index for the five routes from Framer's own index file
// (the JSON its search component fetched), rewriting the template's paths to
// the rebuild's routes. Pages the rebuild does not ship are dropped.
import fs from 'node:fs';
const source = JSON.parse(fs.readFileSync('D:/exporter/exports/oxv/_work/searchIndex.json', 'utf8'));
const ROUTES = { '/': '/', '/about-us': '/about', '/programs': '/programs', '/contact-us': '/contact' };
// The template's pages share one document title and split their hero titles
// across several h1/h2 layers, so each route gets a readable name here.
const NAMES = { '/': 'Home', '/about': 'About Us', '/programs': 'Programs', '/contact': 'Contact Us' };
const entries = [];
for (const [path, entry] of Object.entries(source)) {
  const url = ROUTES[path];
  if (!url) continue;
  const { title, description, h1, h2, h3, h4, h5, h6, p } = entry;
  entries.push({ url, title: NAMES[url], description, h1: [NAMES[url], ...h1], h2, h3, h4, h5, h6, p });
}
fs.writeFileSync(
  'D:/oxversity/src/data/searchIndex.ts',
  `// Generated by _extract/search-index.mjs from the site's own search index.
// One entry per route: the text the search scores against. Regenerate after
// changing page copy, or edit the strings here directly.
import type { SearchEntry } from '@/lib/search';

export const searchIndex: SearchEntry[] = ${JSON.stringify(entries, null, 2)};
`,
);
console.log(entries.length, 'entries');
