// Generated by _extract/appear.mjs from the pages' __framer__appearAnimationsContent
// blobs: the site's real entrance animations, keyed by data-framer-appear-id and
// then by breakpoint hash ("default" = desktop). Regenerate rather than hand-edit.
import type { EffectState, EffectTransition } from './effects';

export interface AppearSpec {
  initial: EffectState;
  animate: EffectState & { transition: EffectTransition };
}

export const appearAnimations: Record<string, Record<string, AppearSpec>> = {
  "1kv7kk8": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1.03,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 0
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.9,
          "ease": [
            0.58,
            0.01,
            0.29,
            0.95
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    },
    "11qy7e3": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1.03,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 0
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.9,
          "ease": [
            0.58,
            0.01,
            0.29,
            0.95
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    },
    "1n3ggvs": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1.03,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 0
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.9,
          "ease": [
            0.58,
            0.01,
            0.29,
            0.95
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    },
    "4h95au": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1.03,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 0
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.9,
          "ease": [
            0.58,
            0.01,
            0.29,
            0.95
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    },
    "1ppn25y": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1.03,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 0
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.9,
          "ease": [
            0.58,
            0.01,
            0.29,
            0.95
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "1rsz9n2": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "101pojn": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0.3,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "1slilnr": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 40,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 40
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0.3,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    },
    "1n3ggvs": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 40,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 40
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0.3,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    },
    "11qy7e3": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 40,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 40
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0.3,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "hero-acronym": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 20
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "1xedpim": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 40,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 40
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0.1,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "81btpf": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 60,
          "delay": 0.2,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    },
    "1n3ggvs": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 60,
          "delay": 0.2,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    },
    "11qy7e3": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 60,
          "delay": 0.2,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "ny0p9m": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 60,
          "delay": 0.2,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    },
    "1n3ggvs": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 60,
          "delay": 0.2,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    },
    "11qy7e3": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 60,
          "delay": 0.2,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "aazozd": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "otiu90": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0.3,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "v723o2": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 40,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 40
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0.3,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "bmw3ek": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "1wtv2py": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 60
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0.3,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "frp2eo": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 40,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 40
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "damping": 100,
          "delay": 0.3,
          "mass": 1,
          "stiffness": 400,
          "type": "spring"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "e0drya": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": -40,
        "y": 0
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.7,
          "ease": [
            0.44,
            0,
            0.56,
            1
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    },
    "19nkl0n": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": -40,
        "y": 0
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.7,
          "ease": [
            0.44,
            0,
            0.56,
            1
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    },
    "5echh6": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 40
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.7,
          "ease": [
            0.44,
            0,
            0.56,
            1
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    }
  },
  "sohjjt": {
    "default": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 40,
        "y": 0
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.7,
          "ease": [
            0.44,
            0,
            0.56,
            1
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    },
    "19nkl0n": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 40,
        "y": 0
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.7,
          "ease": [
            0.44,
            0,
            0.56,
            1
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    },
    "5echh6": {
      "initial": {
        "opacity": 0.001,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": 40
      },
      "animate": {
        "opacity": 1,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "transition": {
          "delay": 0,
          "duration": 0.7,
          "ease": [
            0.44,
            0,
            0.56,
            1
          ],
          "type": "tween"
        },
        "x": 0,
        "y": 0
      }
    }
  }
};

/**
 * Framer's text effect on the "OX Versity" hero titles: each character starts
 * 80px low and transparent and springs up, 0.1s after the one before, once the
 * title's own entrance has been running for 0.4s.
 */
export const TEXT_EFFECT = {
  effect: { opacity: 0.001, rotate: 0, scale: 1, skewX: 0, skewY: 0, x: 0, y: 80 } as EffectState,
  startDelay: 0.4,
  stagger: 0.1,
  transition: { bounce: 0.25, duration: 1, type: 'spring' } as EffectTransition,
};
