// Generated by _extract/effects.mjs from the site's JavaScript bundles.
// Framer's own scroll effect specs. Regenerate rather than editing by hand.

export interface EffectTransition {
  type?: 'spring' | 'tween';
  damping?: number;
  stiffness?: number;
  mass?: number;
  delay?: number;
  duration?: number;
  ease?: number[];
  bounce?: number;
  stagger?: number;
}

export interface EffectState {
  opacity?: number;
  x?: number;
  y?: number;
  scale?: number;
  rotate?: number;
  rotateX?: number;
  rotateY?: number;
  skewX?: number;
  skewY?: number;
  transition?: EffectTransition | null;
}

/** An "appear on scroll" effect: replayed when the element enters the viewport. */
export interface AppearEffect {
  transition: EffectTransition | null;
  enter: EffectState | null;
  exit: EffectState | null;
  once: boolean;
  threshold: number;
  targetOpacity: number;
  scrollDirection?: { direction: 'up' | 'down'; target: EffectState | null };
}

/** A scroll-linked transform: interpolated between targets as the element crosses the viewport. */
export interface TransformEffect {
  spring: EffectTransition | null;
  targets: { target: EffectState | null }[] | null;
  trigger: string | undefined;
  threshold: number;
  module: string;
}

export interface LoopEffect {
  loop: EffectState | null;
  transition: EffectTransition | null;
  repeatType: string;
  repeatDelay: number;
  module: string;
}

export const appearEffects: Record<string, AppearEffect> = {
  "framer-y5ruxh-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1oodo97": {
    "transition": {
      "delay": 0.3,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.3,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-tq0j24": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1lks04t": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1edsx6u": {
    "transition": {
      "delay": 0.3,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.3,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1u1o8a3": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1.1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1.1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1awlqq4": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-y4qhjj": {
    "transition": {
      "delay": 0.3,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.3,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1gdabvi": {
    "transition": {
      "damping": 60,
      "delay": 0,
      "mass": 1,
      "stiffness": 500,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 60
    },
    "exit": null,
    "once": true,
    "threshold": 0.5,
    "targetOpacity": 1
  },
  "framer-1goa3az": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-njgqbr": {
    "transition": null,
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-7cnolh-container": {
    "transition": {
      "damping": 60,
      "delay": 0,
      "mass": 1,
      "stiffness": 500,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": null,
    "once": true,
    "threshold": 0.5,
    "targetOpacity": 1
  },
  "framer-18cbtr2-container": {
    "transition": {
      "damping": 60,
      "delay": 0,
      "mass": 1,
      "stiffness": 500,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": null,
    "once": true,
    "threshold": 0.5,
    "targetOpacity": 1
  },
  "framer-1u2a99c": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-35jjhq": {
    "transition": {
      "damping": 100,
      "delay": 0.1,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-7v1wrm": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 60
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 60
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-foys6q-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1ymzcfk": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 30
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-c0d2d7": {
    "transition": {
      "damping": 100,
      "delay": 0.1,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 30
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1tkakbu-container": {
    "transition": {
      "damping": 60,
      "delay": 0,
      "mass": 1,
      "stiffness": 500,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": null,
    "once": true,
    "threshold": 0.5,
    "targetOpacity": 1
  },
  "framer-bibtxh-container": {
    "transition": {
      "damping": 60,
      "delay": 0,
      "mass": 1,
      "stiffness": 500,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": null,
    "once": true,
    "threshold": 0.5,
    "targetOpacity": 1
  },
  "framer-14ikicq-container": {
    "transition": {
      "damping": 60,
      "delay": 0,
      "mass": 1,
      "stiffness": 500,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": null,
    "once": true,
    "threshold": 0.5,
    "targetOpacity": 1
  },
  "framer-13m21ni": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-onbweg": {
    "transition": {
      "damping": 100,
      "delay": 0.1,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1sen24b-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 60
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 60
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1938cx9-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-xjwpuc": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1cuqyk1": {
    "transition": {
      "damping": 100,
      "delay": 0.1,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-arxw4x-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-bmvoqh-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": -40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": -40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1yjpdms-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1g89kp2": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-831eai": {
    "transition": {
      "damping": 100,
      "delay": 0.1,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-5mov61-container": {
    "transition": {
      "damping": 60,
      "delay": 0,
      "mass": 1,
      "stiffness": 500,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": null,
    "once": true,
    "threshold": 0.5,
    "targetOpacity": 1
  },
  "framer-1r2mtj3-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-4kzgrb-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1yas68c-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": -40,
      "y": 0
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-es9y1s-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 40,
      "y": 0
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1k0hynk-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": -40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": -40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1lkvypt-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-kgxlq9-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-sitldl-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": -40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": -40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-16kek0h-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1ex6962-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-gdyxm0-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": -40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": -40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-qjtaqi-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-ziamzv": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1bqoyud": {
    "transition": {
      "damping": 100,
      "delay": 0.1,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-wpiv40": {
    "transition": null,
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 60
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": null,
      "x": 0,
      "y": 60
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-qoim7z": {
    "transition": {
      "delay": 0.3,
      "duration": 0.4,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.3,
        "duration": 0.4,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 80
    },
    "once": false,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-oabdj9-container": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 60
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-11yw4oy-container": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 60
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-xv32t5-container": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 60
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1ye3mgd": {
    "transition": null,
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1.1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1.1,
      "skewX": 0,
      "skewY": 0,
      "transition": null,
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-827vqi": {
    "transition": null,
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": null,
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-pu95g6": {
    "transition": {
      "delay": 0.1,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.1,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1pscora": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-19s4tb": {
    "transition": {
      "delay": 0.3,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1.1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1.1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.3,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-vdgpqe-container": {
    "transition": {
      "delay": 0.4,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.4,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-f9aycm": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-gji2wv": {
    "transition": {
      "damping": 100,
      "delay": 0.1,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1sfkeuf-container": {
    "transition": null,
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": null,
      "x": 40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-6dunz9-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1poxkoa-container": {
    "transition": null,
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": null,
      "x": 40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-18d1vlg-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-ql88yr": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1s604ar-container": {
    "transition": {
      "delay": 0.3,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.3,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-ymchr3": {
    "transition": {
      "delay": 0.3,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.3,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-cmpf1g-container": {
    "transition": {
      "delay": 0.4,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.4,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-on8kep": {
    "transition": {
      "delay": 0.4,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.4,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-ypp3ea-container": {
    "transition": {
      "delay": 0.5,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.5,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1bdck2s": {
    "transition": {
      "delay": 0.5,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.5,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1kr2f3i-container": {
    "transition": {
      "delay": 0.6,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.6,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-wpk82": {
    "transition": {
      "delay": 0.6,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.6,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1j6sz9e-container": {
    "transition": {
      "delay": 0.7,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.7,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-16033z5": {
    "transition": {
      "delay": 0.7,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.7,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-l9v3kt": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 80
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-15btzim": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-681mt8": {
    "transition": {
      "damping": 100,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1mdk9ly": {
    "transition": {
      "damping": 100,
      "delay": 0.1,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 80
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1p325na-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-8z33gg-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1jkp1ih-container": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 40,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 40,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-easkis": {
    "transition": {
      "damping": 60,
      "delay": 0,
      "mass": 1,
      "stiffness": 400,
      "type": "spring"
    },
    "enter": {
      "opacity": 1,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1.1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 1,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1.1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "damping": 60,
        "delay": 0,
        "mass": 1,
        "stiffness": 400,
        "type": "spring"
      },
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0.5,
    "targetOpacity": 1
  },
  "framer-1acrwa0": {
    "transition": {
      "damping": 100,
      "delay": 0.5,
      "mass": 1,
      "stiffness": 300,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": null,
    "once": true,
    "threshold": 0.5,
    "targetOpacity": 1
  },
  "framer-3y0d32-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-rbh95m-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1kb7ve3-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1gswekf-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1pccm2e-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-tbsgjl-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1dx9ps-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-pz4vch-container": {
    "transition": {
      "delay": 0.2,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.2,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1ud454q": {
    "transition": {
      "delay": 0.3,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.3,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 0
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1vlsrm5": {
    "transition": {
      "delay": 0,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-rsoue6-container": {
    "transition": {
      "delay": 0.1,
      "duration": 0.7,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "type": "tween"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "transition": {
        "delay": 0.1,
        "duration": 0.7,
        "ease": [
          0.44,
          0,
          0.56,
          1
        ],
        "type": "tween"
      },
      "x": 0,
      "y": 40
    },
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-1wha7z8": {
    "transition": {
      "damping": 60,
      "delay": 0,
      "mass": 1,
      "stiffness": 500,
      "type": "spring"
    },
    "enter": {
      "opacity": 0,
      "rotate": 0,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 40
    },
    "exit": null,
    "once": true,
    "threshold": 0,
    "targetOpacity": 1
  },
  "framer-yg91o4-container": {
    "transition": {
      "damping": 40,
      "delay": 0,
      "mass": 1,
      "stiffness": 300,
      "type": "spring"
    },
    "enter": null,
    "exit": null,
    "once": false,
    "threshold": 0.5,
    "targetOpacity": 1,
    "scrollDirection": {
      "direction": "down",
      "target": null
    }
  },
  "framer-4kmgod-container": {
    "transition": {
      "damping": 40,
      "delay": 0,
      "mass": 1,
      "stiffness": 300,
      "type": "spring"
    },
    "enter": null,
    "exit": null,
    "once": false,
    "threshold": 0.5,
    "targetOpacity": 1,
    "scrollDirection": {
      "direction": "down",
      "target": {
        "opacity": 0,
        "rotate": 0,
        "rotateX": 0,
        "rotateY": 0,
        "scale": 1,
        "skewX": 0,
        "skewY": 0,
        "x": 0,
        "y": -120
      }
    }
  }
};

export const transformEffects: Record<string, TransformEffect> = {
  "framer-1u5mh4-container": {
    "spring": {
      "damping": 100,
      "delay": 0,
      "duration": 0.3,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "mass": 1,
      "stagger": 0,
      "stiffness": 250,
      "type": "spring"
    },
    "targets": [
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      },
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1.15,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      }
    ],
    "trigger": "onScrollTarget",
    "threshold": 0.5,
    "module": "1-bGvbKm5qba"
  },
  "framer-1n96xeg-container": {
    "spring": {
      "damping": 100,
      "delay": 0,
      "duration": 0.3,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "mass": 1,
      "stagger": 0,
      "stiffness": 250,
      "type": "spring"
    },
    "targets": [
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      },
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1.15,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      }
    ],
    "trigger": "onScrollTarget",
    "threshold": 0.5,
    "module": "8OAyH4qqX2mH"
  },
  "framer-w3iya1-container": {
    "spring": {
      "damping": 100,
      "delay": 0,
      "duration": 0.3,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "mass": 1,
      "stagger": 0,
      "stiffness": 250,
      "type": "spring"
    },
    "targets": [
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      },
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1.15,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      }
    ],
    "trigger": "onScrollTarget",
    "threshold": 0.5,
    "module": "ao9GpfYQCfYg"
  },
  "framer-1tpa2o2-container": {
    "spring": {
      "damping": 100,
      "delay": 0,
      "duration": 0.3,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "mass": 1,
      "stagger": 0,
      "stiffness": 250,
      "type": "spring"
    },
    "targets": [
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      },
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1.15,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      }
    ],
    "trigger": "onScrollTarget",
    "threshold": 0.5,
    "module": "JYwI76K8hHPs"
  },
  "framer-1x3z8yx": {
    "spring": {
      "damping": 80,
      "delay": 0,
      "duration": 0.3,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "mass": 1,
      "stagger": 0,
      "stiffness": 500,
      "type": "spring"
    },
    "targets": [
      {
        "target": {
          "opacity": 0,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 308,
          "y": 0
        }
      },
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      }
    ],
    "trigger": "onScrollTarget",
    "threshold": 1,
    "module": "JYwI76K8hHPs"
  },
  "framer-qoim7z": {
    "spring": {
      "damping": 60,
      "delay": 0,
      "duration": 0.3,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "mass": 1,
      "stagger": 0,
      "stiffness": 500,
      "type": "spring"
    },
    "targets": [
      {
        "target": {
          "opacity": 0,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 80
        }
      },
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      }
    ],
    "trigger": "onScrollTarget",
    "threshold": 1,
    "module": "JYwI76K8hHPs"
  },
  "framer-akmuco": {
    "spring": {
      "damping": 80,
      "delay": 0,
      "duration": 0.3,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "mass": 1,
      "stagger": 0,
      "stiffness": 500,
      "type": "spring"
    },
    "targets": [
      {
        "target": {
          "opacity": 0,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": -323,
          "y": 0
        }
      },
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      }
    ],
    "trigger": "onScrollTarget",
    "threshold": 1,
    "module": "JYwI76K8hHPs"
  },
  "framer-cfp9ri-container": {
    "spring": {
      "damping": 100,
      "delay": 0,
      "duration": 0.3,
      "ease": [
        0.44,
        0,
        0.56,
        1
      ],
      "mass": 1,
      "stagger": 0,
      "stiffness": 250,
      "type": "spring"
    },
    "targets": [
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      },
      {
        "target": {
          "opacity": 1,
          "rotate": 0,
          "rotateX": 0,
          "rotateY": 0,
          "scale": 1.15,
          "skewX": 0,
          "skewY": 0,
          "x": 0,
          "y": 0
        }
      }
    ],
    "trigger": "onScrollTarget",
    "threshold": 0.5,
    "module": "n0RHhXYeCuUs"
  }
};

export const loopEffects: Record<string, LoopEffect> = {
  "framer-14ty0pd": {
    "loop": {
      "opacity": 1,
      "rotate": 360,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "transition": {
      "delay": 0,
      "duration": 1,
      "ease": [
        0,
        0,
        1,
        1
      ],
      "type": "tween"
    },
    "repeatType": "loop",
    "repeatDelay": 0,
    "module": "1-bGvbKm5qba"
  },
  "framer-1cljni": {
    "loop": {
      "opacity": 1,
      "rotate": 360,
      "rotateX": 0,
      "rotateY": 0,
      "scale": 1,
      "skewX": 0,
      "skewY": 0,
      "x": 0,
      "y": 0
    },
    "transition": {
      "delay": 0,
      "duration": 1,
      "ease": [
        0,
        0,
        1,
        1
      ],
      "type": "tween"
    },
    "repeatType": "loop",
    "repeatDelay": 0,
    "module": "J0Xtptg8Q"
  }
};
